# SecuNetConfigWin

DeviceConfiguration: {
  # Network Interface Configuration
  NetworkInterface: {
    name: "Ethernet",
    Commands: [
      # Disable the network interface
      { command: disable },
      # Set IPv4 address
      { command: set, type: ipv4, address: "127.0.0.1", netmask: "255.255.255.0" },
      # Set IPv6 address
      { command: set, type: ipv6, address: "::1", prefix: 128 },
      # Enable the network interface
      { command: enable }
    ]
  },
  
  # Hostname Configuration
  Hostname: {
    # Change hostname to localhost
    Statement: { command: set, value: "localhost" }
  },

  # MAC Address Configuration
  MACAddress: {
    interface: "Ethernet",
    Commands: [
      # Disable the network interface
      { command: disable },
      # Change MAC address to all zeros
      { command: set, address: "00-00-00-00-00-00" },
      # Enable the network interface
      { command: enable }
    ]
  },

  # Bluetooth Configuration
  Bluetooth: {
    interface: "Bluetooth Device",
    Commands: [
      # Disable Bluetooth interface
      { command: disable },
      # Enable Bluetooth interface
      { command: enable },
      # Change Bluetooth device name to localhost
      { command: set, name: "localhost" },
      # Make Bluetooth discoverable
      { command: discoverable }
    ]
  },

  # Services Management
  Services: {
    Commands: [
      # Stop the GPS Location service
      { service: "lfsvc", command: stop },
      # Disable the GPS Location service
      { service: "lfsvc", command: disable }
    ]
  },

  # Firewall Rules
  Firewall: {
    Rules: [
      # Block all ICMP echo requests (pings)
      { command: OUTPUT, protocol: icmpv4, icmp-type: echo-request, target: BLOCK },
      # Block all incoming traffic
      { command: INPUT, target: BLOCK }
    ]
  },

  # Browser Cache and Cookies Clearing
  Browser: {
    ClearCacheAndCookies: [
      # Clear cache and cookies for Google Chrome
      { browser: chrome, options: "--clear-cache --clear-cookies" },
      # Clear cache and cookies for Firefox
      { browser: firefox, options: "--clear-cache --clear-cookies" },
      # Clear cache and cookies for Microsoft Edge
      { browser: edge, options: "--clear-cache --clear-cookies" }
    ]
  }
}
