# Secunetcon for Unix-based Systems

DeviceConfiguration: {
  # Network Interface Configuration
  NetworkInterface: {
    name: eth0,
    Commands: [
      # Bring the interface down
      { command: down },
      # Set IPv4 address
      { command: inet, address: 127.0.0.1 },
      # Set IPv6 address
      { command: inet6, address: "::1" },
      # Bring the interface down (again, before changing MAC address)
      { command: down },
      # Change MAC address to all zeros
      { command: hw, address: "00:00:00:00:00:00" },
      # Bring the interface up
      { command: up }
    ]
  },
  
  # Hostname Configuration
  Hostname: {
    # Change hostname to localhost
    Statement: { command: set, value: 127.0.0.1 }
  },

  # Bluetooth Configuration
  Bluetooth: {
    interface: hci0,
    Commands: [
      # Bring Bluetooth interface down
      { command: down },
      # Bring Bluetooth interface up
      { command: up },
      # Change Bluetooth device name to localhost
      { command: name, value: localhost },
      # Make Bluetooth discoverable
      { command: piscan }
    ]
  },

  # Services Management
  Services: {
    Commands: [
      # Stop the ModemManager service
      { service: ModemManager, command: stop },
      # Disable the ModemManager service
      { service: ModemManager, command: disable }
    ]
  },

  # Firewall Rules
  Firewall: {
    Rules: [
      # Block all ICMP echo requests (pings)
      { command: OUTPUT, protocol: icmp, icmp-type: echo-request, target: DROP },
      # Block all incoming traffic
      { command: INPUT, target: DROP }
    ]
  },

  # Browser Cache and Cookies Clearing
  Browser: {
    ClearCacheAndCookies: [
      # Clear cache and cookies for Google Chrome
      { browser: google-chrome, options: "--clear-cache --clear-cookies" },
      # Clear cache and cookies for Firefox
      { browser: firefox, options: "--clear-cache --clear-cookies" }
    ]
  }
}

# Secunetcon. Copyright © 2024. Joseph D. Smith. All Rights Reserved.
