# Windows Secunetcon

network_settings:
  - command: ipconfig /release
    comment: Release IP address
  - command: ipconfig /renew
    comment: Renew IP address
  - command: netsh interface ipv4 set address "Ethernet" static 127.0.0.1
    comment: Assign localhost IP (replace "Ethernet" with actual adapter name)

hostname:
  - command: hostname localhost
    comment: Change hostname to localhost

mac_address:
  - command: reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4D36E972-E325-11CE-BFC1-08002bE10318}\0000" /v NetworkAddress /d "000000000000"
    comment: Change MAC address to all zeros (replace "0000" with adapter ID)

bluetooth_address:
  - command: reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\BTHPORT\Parameters\Keys\001122334455" /v Name /d "localhost"
    comment: Change Bluetooth name to localhost
  - command: reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\BTHPORT\Parameters\Keys\001122334455" /v EnableLMPiscan /d 1 /t REG_DWORD /f
    comment: Enable Bluetooth discovery

location_services:
  - command: net stop "SensorDataService"
    comment: Disable location services

firewall:
  - command: netsh advfirewall firewall add rule name="Block ICMP" protocol=icmpv4:any,any action=block
    comment: Close pings
  - command: netsh advfirewall set allprofiles firewallpolicy blockinbound
    comment: Block all ingress traffic

browser_cleanup:
  - command: start chrome --clear-ssl-state --incognito
    comment: Clear browser cookies and cache for Chrome
  - command: start firefox --no-remote -ProfileManager
    comment: Clear browser cookies and cache for Firefox
  - command: start brave --clear-browsing-data
    comment: Clear browser cookies and cache for Brave
  - command: start vivaldi --clearprivatedata
    comment: Clear browser cookies and cache for Vivaldi
  - command: start msedge --clear-browser-data
    comment: Clear browser cookies and cache for Edge

disk_encryption:
  - command: manage-bde -on C: -RecoveryPassword
    comment: Enable BitLocker encryption for drive C:

browser_encryption:
  - command: "C:\Program Files\Mozilla Firefox\firefox.exe" -CreateProfile "encrypted-profile"
    comment: Create encrypted Firefox profile
  - command: encfs "C:\Users\.\AppData\Roaming\Mozilla\Firefox\Profiles\encrypted-profile" "C:\Users\.\AppData\Roaming\Mozilla\Firefox\Profiles\plain-profile"
    comment: Mount encrypted Firefox profile
  - command: "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --user-data-dir="C:\Users\.\AppData\Local\Google\Chrome\encrypted-profile"
    comment: Create encrypted Chrome profile
  - command: encfs "C:\Users\.\AppData\Local\Google\Chrome\encrypted-profile" "C:\Users\.\AppData\Local\Google\Chrome\plain-profile"
    comment: Mount encrypted Chrome profile
  - command: "C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe" --user-data-dir="C:\Users\.\AppData\Local\BraveSoftware\Brave-Browser\encrypted-profile"
    comment: Create encrypted Brave profile
  - command: encfs "C:\Users\.\AppData\Local\BraveSoftware\Brave-Browser\encrypted-profile" "C:\Users\.\AppData\Local\BraveSoftware\Brave-Browser\plain-profile"
    comment: Mount encrypted Brave profile
  - command: "C:\Program Files\Vivaldi\Application\vivaldi.exe" --user-data-dir="C:\Users\.\AppData\Local\Vivaldi\encrypted-profile"
    comment: Create encrypted Vivaldi profile
  - command: encfs "C:\Users\.\AppData\Local\Vivaldi\encrypted-profile" "C:\Users\.\AppData\Local\Vivaldi\plain-profile"
    comment: Mount encrypted Vivaldi profile
    
# Secunetcon. Copyright © 2024. Joseph D. Smith. Licensed under Apache 2.0
